// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNL-FBJIj3-Ey4VpXjUn64eZYDc6SzqlM',
    appId: '1:195792347168:web:ad3393fa28e63719b19c45',
    messagingSenderId: '195792347168',
    projectId: 'quiz320-4',
    authDomain: 'quiz320-4.firebaseapp.com',
    storageBucket: 'quiz320-4.appspot.com',
    measurementId: 'G-372B9NQRSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapbc8mtr2dN6ieFTT-6FvIekUEn-TnZw',
    appId: '1:195792347168:android:bded57c2cd77994db19c45',
    messagingSenderId: '195792347168',
    projectId: 'quiz320-4',
    storageBucket: 'quiz320-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7P7XNrHLCWEMSXQYOgmLsQ3YTBbvJ0Uk',
    appId: '1:195792347168:ios:d09441efe6b84bbeb19c45',
    messagingSenderId: '195792347168',
    projectId: 'quiz320-4',
    storageBucket: 'quiz320-4.appspot.com',
    iosBundleId: 'com.example.quiz3204',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7P7XNrHLCWEMSXQYOgmLsQ3YTBbvJ0Uk',
    appId: '1:195792347168:ios:d09441efe6b84bbeb19c45',
    messagingSenderId: '195792347168',
    projectId: 'quiz320-4',
    storageBucket: 'quiz320-4.appspot.com',
    iosBundleId: 'com.example.quiz3204',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNL-FBJIj3-Ey4VpXjUn64eZYDc6SzqlM',
    appId: '1:195792347168:web:689678a083d693b6b19c45',
    messagingSenderId: '195792347168',
    projectId: 'quiz320-4',
    authDomain: 'quiz320-4.firebaseapp.com',
    storageBucket: 'quiz320-4.appspot.com',
    measurementId: 'G-9E3KTY140L',
  );
}
